### PR TITLE
Fix issues #168, #199

### LINKED ISSUE #168: Add osmosis mainnet ChainInfo to networks
We currently missing mainnet ChainInfo on osmosis https://github.com/AbstractSDK/cw-orchestrator/blob/13c11e4480a905dd4ff31a74e0bfa58b098d9b0d/cw-orch/src/daemon/networks/osmosis.rs
Yep, we can't deploy on mainnet, but we still can do other txs, as well as it will be useful for osmosis-test-tube

### LINKED ISSUE #199: Update `event_attr_value`'s error to know which key is missing
https://github.com/AbstractSDK/cw-orchestrator/blob/75b0d71d70baec6af6ac82031de9af0e9ec4df10/packages/cw-orch-core/src/environment/index_response.rs#L90

Just ran into that error:
```
running 1 test
Error: Generic error: missing 

Caused by:
    Generic error: missing
```

### PR DESCRIPTION
**Pull request by Kayanski**
This PR aims at fixing small issues 

Closes #199 : Better errors for getting events in Tx object
Closes #168 : Adding Osmosis_1 support

### CODE REVIEW

**Review by CyberHoward — APPROVED** [review]

File: packages/cw-orch-core/src/environment/index_response.rs [hunk 1]
```diff
@@ -87,7 +87,10 @@ impl IndexResponse for AppResponse {
                 }
             }
         }
-        Err(StdError::generic_err("missing "))
+        Err(StdError::generic_err(format!(
+            "missing combination (event: {}, attribute: {})",
+            event_type, attr_key
+        )))
```
Comment (Buckram123) [inline packages/cw-orch-core/src/environment/index_response.rs:93]: Much clearer!

**Review by Buckram123 — APPROVED** [review]
TYSM
